server:
  port: 8080
spring:
  application:
    name: simple-e-commerce-v2
  datasource:
    url: jdbc:h2:mem:ecommercedb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: embedded
  sql:
    init:
      encoding: utf-8
      schema-locations: classpath:schema_h2.sql
      data-locations: classpath:data_h2.sql
      mode: always

  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop # Hibernate ddl auto (create, create-drop, validate, update)

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: ps.demo.entity

springdoc:
  packagesToScan: ps.demo
  writer-with-default-pretty-printer: true
  api-docs.enabled: true
  api-docs.path: /springdoc/api-docs
  resolve-schema-properties: true
  swagger-ui:
    enabled: true
    path: /springdoc/index.html
    url: /springdoc/api-docs
    displayRequestDuration: true
    showExtensions: true
    showCommonExtensions: true
    disable-swagger-default-url: true
    operationsSorter: method
swagger:
  application-name: ${spring.application.name}
  application-version: 1.0.0
  application-description: Openapi Springdoc
  try-host: http://localhost:8080
