server:
  port: 8080
spring:
  application:
    name: simple-e-commerce-v2
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:ecommercedb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: ps.demo.entity

springdoc:
  api-docs.enabled: false
  swagger-ui:
    enabled: false